version: '3'

services:
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    ports:
      - 1880:1880
    volumes:
      - node-red:/data
    restart: always
    networks:
      - internal

  influxdb:
    image: influxdb:1.7
    container_name: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_ORG=iot
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin
      - DOCKER_INFLUXDB_INIT_BUCKET=iot-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mega-super-secret-123!
    ports:
      - 8086:8086
    volumes:
      - influxdb:/var/lib/influxdb
      - ./init.iql:/docker-entrypoint-initdb.d/init.iql:ro
    restart: always
    networks:
      - internal

  grafana:
    image: grafana/grafana:5.4.3
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
    restart: always
    networks:
      - internal

  # mqttbridge:
  #   build: ../02-bridge
  #   image: iothon/mqttbridge
  #   container_name: mqttbridge
  #   depends_on:
  #     - mosquitto
  #     - influxdb
  #   restart: always
  #   networks:
  #     - internal

networks:
  internal:
    driver: bridge

volumes:
  influxdb: { driver: local }
  grafana: { driver: local }
  node-red:
